#
# Copyright (c) 2024-2025 Oleg Yukhnevich. Use of this source code is governed by the Apache 2.0 license.
#

group=dev.whyoleg.sweetspi
version=0.1.2
#Gradle
org.gradle.kotlin.dsl.skipMetadataVersionCheck=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2g
