/*
 * Copyright (c) 2025 Oleg Yukhnevich. Use of this source code is governed by the Apache 2.0 license.
 */

package dev.whyoleg.sweetspi

@Service
public interface SomeApi {
    public fun someFunction(): String

    // generated by compiler plugin
    public companion object Default : SomeApi by Bootstrap.get()

    // generated by compiler plugin
    public object Bootstrap {
        internal fun get(): SomeApi = TODO()
    }
}

@Target(AnnotationTarget.ANNOTATION_CLASS)
public annotation class ServiceInfo

// when sometimes needed
@ServiceInfo
public annotation class SomeMetadata(
    val value: String,
)

public class LazyServiceProvider<T>(
    public val annotations: List<Annotation>,
    initializer: () -> T,
) : Lazy<T> by lazy(initializer)

@SomeMetadata("Hello world")
@ServiceProvider
public fun impl(): SomeApi = TODO()

// implementation will be generated
public interface ServiceLoader2<T> {
    public fun loadAll(): Sequence<T>
}
