/*
 * Copyright (c) 2024 Oleg Yukhnevich. Use of this source code is governed by the Apache 2.0 license.
 */

@file:Suppress("PackageDirectoryMismatch")

package dev.whyoleg.sweetspi.internal

import kotlin.reflect.*

@RequiresOptIn("Internal API for KSP processor, should not be used outside", RequiresOptIn.Level.ERROR)
public annotation class InternalSweetSpiApi

// there should be one such initializer generated by KSP per module/platform/sourceSet where KSP plugin is applied
@InternalSweetSpiApi
public interface InternalServiceModule {
    public val services: Set<KClass<*>>
    public val requiredServices: Set<KClass<*>>
    public fun providers(cls: KClass<*>): List<*>
}

internal expect open class SynchronizedObject()

internal expect inline fun <T> synchronized(lock: SynchronizedObject, block: () -> T): T

@InternalSweetSpiApi
internal expect fun getAvailableModules(): List<InternalServiceModule>

@InternalSweetSpiApi
internal object InternalServiceLoader : SynchronizedObject() {
    private val providerCache = mutableMapOf<Pair<KClass<out InternalServiceModule>, KClass<*>>, List<*>>()

    internal fun <T : Any> getProviders(module: InternalServiceModule, service: KClass<T>, reload: Boolean = false): List<T> {
        val original = if (reload) null else providerCache[module::class to service]
        @Suppress("UNCHECKED_CAST") val value = (original ?: module.providers(service)) as List<T>
        providerCache[module::class to service] = value
        return value
    }

    fun <T : Any> load(cls: KClass<T>, reloadProviders: Boolean = false): List<T> {
        return load(getAvailableModules(), cls, reloadProviders)
    }

    fun <T : Any> load(modules: List<InternalServiceModule>, cls: KClass<T>, reloadProviders: Boolean = false): List<T> {
        return synchronized(this) {
            modules.flatMap { getProviders(it, cls, reloadProviders) }
        }
    }
}
